package com.app.profile.controller;

import com.app.profile.dto.DesignPanelUpdateRequest;
import com.app.profile.dto.DesignRequest;
import com.app.profile.dto.AutoDesignRequest;
import com.app.profile.dto.DesignResponse;
import com.app.profile.service.DesignService;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

@RestController("profileDesignController")
@RequestMapping("/api/designs")
@PreAuthorize("hasAnyRole('ADMIN', 'SALES', 'PRODUCTION')")
public class DesignController {

    private final DesignService designService;
    private final com.app.profile.service.AiParsingService aiParsingService;

    public DesignController(DesignService designService, com.app.profile.service.AiParsingService aiParsingService) {
        this.designService = designService;
        this.aiParsingService = aiParsingService;
    }

    @PostMapping("/from-text")
    public ResponseEntity<DesignResponse> generateDesignFromText(@RequestBody java.util.Map<String, String> request) {
        String text = request.get("text");
        DesignRequest designRequest = aiParsingService.parseFromText(text);
        DesignResponse response = designService.generateDesign(designRequest);
        return ResponseEntity.ok(response);
    }

    @PostMapping("/generate")
    public ResponseEntity<DesignResponse> generateDesign(@RequestBody DesignRequest request) {
        DesignResponse response = designService.generateDesign(request);
        return ResponseEntity.ok(response);
    }

    @PostMapping("/auto-generate")
    public ResponseEntity<DesignResponse> autoGenerateDesign(@RequestBody AutoDesignRequest request) {
        DesignResponse response = designService.autoGenerateDesign(request);
        return ResponseEntity.ok(response);
    }

    @PatchMapping("/{designId}/panels/{panelId}")
    public ResponseEntity<DesignResponse> updatePanel(
            @PathVariable("designId") java.util.UUID designId,
            @PathVariable("panelId") java.util.UUID panelId,
            @RequestBody DesignPanelUpdateRequest request) {
        DesignResponse response = designService.updatePanel(designId, panelId, request);
        return ResponseEntity.ok(response);
    }
}
