-- V11__relax_design_constraints.sql

ALTER TABLE designs ALTER COLUMN project_id DROP NOT NULL;
ALTER TABLE designs ALTER COLUMN name DROP NOT NULL;
ALTER TABLE designs ALTER COLUMN system_id DROP NOT NULL;
ALTER TABLE designs ALTER COLUMN width DROP NOT NULL;
ALTER TABLE designs ALTER COLUMN height DROP NOT NULL;

ALTER TABLE design_panels ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE design_panels ADD COLUMN IF NOT EXISTS panel_type VARCHAR(255) DEFAULT 'GLASS';
