-- V6__alter_design_panels.sql

ALTER TABLE design_panels
ADD COLUMN IF NOT EXISTS panel_index INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS width_mm NUMERIC(10,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS height_mm NUMERIC(10,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS frame_length NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS mullion_length NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS glass_sqft NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS glass_type VARCHAR(255),
ADD COLUMN IF NOT EXISTS mesh_type VARCHAR(255);
