-- V7__fix_design_panels_types.sql

ALTER TABLE design_panels
ALTER COLUMN width_mm TYPE DOUBLE PRECISION,
ALTER COLUMN height_mm TYPE DOUBLE PRECISION,
ALTER COLUMN frame_length TYPE DOUBLE PRECISION,
ALTER COLUMN mullion_length TYPE DOUBLE PRECISION,
ALTER COLUMN glass_sqft TYPE DOUBLE PRECISION;
