-- V9__alter_designs_table.sql

ALTER TABLE designs
ADD COLUMN IF NOT EXISTS width_mm DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS height_mm DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS layout_type VARCHAR(255),
ADD COLUMN IF NOT EXISTS grid_rows INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS grid_cols INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS has_door BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS door_position INTEGER;
